### ISSUE TITLE
Help : DeepEqual Method

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/ToDo_theAteam#12]
need reference for DeepEqual Method for comparing objects
@Ryan2601

**Comment by Ryan2601** [comment]
This is the tape documentation.

https://github.com/substack/tape

search for deepequal/equal to see the difference.

**Comment by Ryan2601** [comment]
![screenshot from 2018-07-10 16-47-38](https://user-images.githubusercontent.com/39595382/42513996-022ba5f8-8461-11e8-9749-e3c73894e63c.png)

**Comment by tawfiknasser** [comment]
:+1:  Thanks
