### ISSUE TITLE
Style - To-dos are large enough

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/ToDo_theAteam#4]
the to-dos to be large enough so that I don't hit the wrong one with my thumb

**Comment by Ryan2601** [comment]
@matthall8 

please check the dome file.
there you will find a comment with your name.
under that you should start styling the container that holds the ToDos.
We will push the latest version of the project in the upcoming minutes.

**Comment by tawfiknasser** [comment]
@matthall8

**Comment by tawfiknasser** [comment]
please review and close if done

**Comment by tawfiknasser** [comment]
@Ryan2601  close if finished

**Comment by Ryan2601** [comment]
done!
