### ISSUE TITLE
Pure function

### ISSUE THREAD

**Issue by DenisKent** [FACN4/ToDo_theAteam#40]
I don't think this would count as a pure function because you are changing the argument "newTodo" without making a copy of it.
You could use JSON.parse(JSON.stringify(newtodo)

https://github.com/FACN4/ToDo_theAteam/blob/7b79fb88010cb63e6a2a9a7588728016511a046e/skeleton/logic.js#L35-L36

**Comment by Ryan2601** [comment]
done :+1:
