### ISSUE TITLE
Vulnerbilities - innerHTML

### ISSUE THREAD

**Issue by DenisKent** [FACN4/ToDo_theAteam#43]
Using .innerHTML opens up vulnerabilities. I was able to insert functioning HTML in to the list. You have used it in several places in the dom.js file. You can replace it with .textContent  .

 
![image](https://user-images.githubusercontent.com/28222381/42619822-cb825d32-85c1-11e8-9811-42c1d7c5178b.png)

https://github.com/FACN4/ToDo_theAteam/blob/7b79fb88010cb63e6a2a9a7588728016511a046e/skeleton/dom.js#L41

**Comment by tawfiknasser** [comment]
:+1: 
The thing is that we are not using any databases,
so this wont affect our original site
only yours site.

but yes i agree with you it should be textContent so the website stay as it should be .

i'll fix this and let you updated
Thanks,
:100:

**Comment by tawfiknasser** [comment]
Fixed , Can you please check again and close the issue if good ?
:1st_place_medal:
