### ISSUE TITLE
Nice work Guys except just one little problem

### ISSUE THREAD

**Issue by yoosefkh** [FACN4/ToDo_theAteam#47]
![screenshot from 2018-07-12 11-19-56](https://user-images.githubusercontent.com/37940433/42621131-a090df1e-85c5-11e8-91bc-936b2196e543.png)
 
but i still like your the design and the "add" button 
also the mark is pretty cool Nice work guys !!

**Comment by Ryan2601** [comment]
:smile: 
great spot you guys!

**Comment by yoosefkh** [comment]
with much love @Ryan2601  <3

**Comment by tawfiknasser** [comment]
#43 same issue 
Fixed , Can you please check again and close the issue if fixed  ?

**Comment by Ryan2601** [comment]
No more giraffes :(
@yoosefkh
