### ISSUE TITLE
Click any part to mark as complete

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/ToDo_theAteam#7]
click on any part of a to-do to mark it as complete so that it's easier for me to check to-dos off

**Comment by tawfiknasser** [comment]
@matthall8 
@Ryan2601 
@afifisuha 
solved this,
please check the last reference and close the issue if you approve

**Comment by Ryan2601** [comment]
when user clicks on the text it marks/unmarks the to do with a line (mark it as done).
